server:
  port: 8083
spring:
  application:
    name: Order-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
  config:
    import: 'optional:configserver:'
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  circuit-breaker:
    instances:
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
management:
  endpoints:
    web:
      exposure:
        include: "*"
